version: '2.14.0'

services:
  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=m4VcZiKaRtVB3ZZ
      - MYSQL_DATABASE=book_store
      - MYSQL_USER=book_store_user
      - MYSQL_PASSWORD=tg8onAn0hTrsswc
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "../generated/datastore/script.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql" 
